let board = { 
    tileSize: 42, 
    offset: 6,  
    xOffset: 34,  
    yOffset: 84 
}; 
const specialCells =[ 
    {line: 0, column: 0, type: 'tripleWord', text: 'Mx3'}, 
    {line: 0, column: 3, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 0, column: 7, type: 'tripleWord', text: 'Mx3'}, 
    {line: 0, column: 11, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 0, column: 14, type: 'tripleWord', text: 'Mx3'}, 
    {line: 1, column: 1, type: 'doubleWord', text: 'Mx2'}, 
    {line: 1, column: 5, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 1, column: 9, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 1, column: 13, type: 'doubleWord', text: 'Mx2'}, 
    {line: 2, column: 2, type: 'doubleWord', text: 'Mx2'}, 
    {line: 2, column: 6, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 2, column: 8, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 2, column: 12, type: 'doubleWord', text: 'Mx2'}, 
    {line: 3, column: 0, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 3, column: 3, type: 'doubleWord', text:  'Mx2'}, 
    {line: 3, column: 7, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 3, column: 11, type: 'doubleWord', text: 'Mx2'}, 
    {line: 3, column: 14, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 4, column: 4, type: 'doubleWord', text: 'Mx2'}, 
    {line: 4, column: 10, type: 'doubleWord', text: 'Mx2'}, 
    {line: 5, column: 1, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 5, column: 5, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 5, column: 9, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 5, column: 13, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 6, column: 2, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 6, column: 6, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 6, column: 8, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 6, column: 12, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 7, column: 0, type: 'tripleWord', text: 'Mx3'}, 
    {line: 7, column: 3, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 7, column: 7, type: 'doubleWord', text: 'Mx2'}, 
    {line: 7, column: 11, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 7, column: 14, type: 'tripleWord', text: 'Mx3'}, 
    {line: 8, column: 2, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 8, column: 6, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 8, column: 8, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 8, column: 12, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 9, column: 1, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 9, column: 5, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 9, column: 9, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 9, column: 13, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 10, column: 4, type: 'doubleWord', text: 'Mx2'}, 
    {line: 10, column: 10, type: 'doubleWord', text: 'Mx2'}, 
    {line: 11, column: 0, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 11, column: 3, type: 'doubleWord', text: 'Mx2'}, 
    {line: 11, column: 7, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 11, column: 11, type: 'doubleWord', text: 'Mx2'}, 
    {line: 11, column: 14, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 12, column: 2, type: 'doubleWord', text: 'Mx2'}, 
    {line: 12, column: 6, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 12, column: 8, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 12, column: 12, type: 'doubleWord', text: 'Mx2'}, 
    {line: 13, column: 1, type: 'doubleWord', text: 'Mx2'}, 
    {line: 13, column: 5, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 13, column: 9, type: 'tripleLetter', text: 'Lx3'}, 
    {line: 13, column: 13, type: 'doubleWord', text: 'Mx2'}, 
    {line: 14, column: 0, type: 'tripleWord', text: 'Mx3'}, 
    {line: 14, column: 3, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 14, column: 7, type: 'tripleWord', text: 'Mx3'}, 
    {line: 14, column: 11, type: 'doubleLetter', text: 'Lx2'}, 
    {line: 14, column: 14, type: 'tripleWord', text: 'Mx3'}, 
];

const lettersDistribution = [ 
    {letter: "*", number: 2, value: 0}, 
    {letter: "A", number: 9, value: 1}, 
    {letter: "B", number: 2, value: 3}, 
    {letter: "C", number: 2, value: 3}, 
    {letter: "D", number: 3, value: 2}, 
    {letter: "E", number: 15, value: 1}, 
    {letter: "F", number: 2, value: 4}, 
    {letter: "G", number: 2, value: 2}, 
    {letter: "H", number: 2, value: 4}, 
    {letter: "I", number: 8, value: 1}, 
    {letter: "J", number: 1, value: 8}, 
    {letter: "K", number: 1, value: 10}, 
    {letter: "L", number: 5, value: 1}, 
    {letter: "M", number: 3, value: 2}, 
    {letter: "N", number: 6, value: 1}, 
    {letter: "O", number: 6, value: 1}, 
    {letter: "P", number: 2, value: 3}, 
    {letter: "Q", number: 1, value: 8}, 
    {letter: "R", number: 6, value: 1}, 
    {letter: "S", number: 6, value: 1}, 
    {letter: "T", number: 6, value: 1}, 
    {letter: "U", number: 6, value: 1}, 
    {letter: "V", number: 2, value: 4}, 
    {letter: "W", number: 1, value: 10}, 
    {letter: "X", number: 1, value: 10}, 
    {letter: "Y", number: 1, value: 10}, 
    {letter: "Z", number: 1, value: 10}, 
]; 